name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      PLATFORMS: linux/amd64
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ env.PLATFORMS }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          load: true
          platforms: ${{ env.PLATFORMS }}
          tags: rootfsimg:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Create directory for plugin container
        run: mkdir rootfs
      - name: Extract image
        run: docker create --name rootfs rootfsimg && docker export rootfs | tar -x -C rootfs
      - name: Create plugin
        run: docker plugin create ${{ secrets.DOCKERHUB_USERNAME }}/glusterfs .
      - name: Print plugin
        run: docker plugin ls
      - name: Publish plugin
        run: docker plugin push ${{ secrets.DOCKERHUB_USERNAME }}/glusterfs
